name: Pecode task cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install
        run: npm install
      - name: Test run
        run: npx cypress run
      - name: Output test results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: mochawesome-report
          retention-days: 20
